import MahlerLean

#print axioms MahlerLean.dyadic_exponent_identity
#print axioms MahlerLean.remainder_exponent_lt_two
#print axioms MahlerLean.farey_exponent_gt_two
#print axioms MahlerLean.perturbation_gap
#print axioms MahlerLean.fusion_exponent_identity
#print axioms MahlerLean.fusion_exponent_negative
#print axioms MahlerLean.exists_safe_center
#print axioms MahlerLean.counting_budget
#print axioms MahlerLean.safety_transfer

#print axioms MahlerLean.mem_sourceFractions
#print axioms MahlerLean.isSafeCenter_iff_no_witness
#print axioms MahlerLean.isSafeCenter_iff_not_mem_dangerousSources
#print axioms MahlerLean.eventually_subquadratic_quarter
#print axioms MahlerLean.exists_safeCenter_of_quarter_bounds
#print axioms MahlerLean.safe_center_of_counting_estimates
#print axioms MahlerLean.safeCenter_avoidance_of_movement

#print axioms MahlerLean.liouville_iff_paperLiouville
#print axioms MahlerLean.liouville_of_source_approximations
#print axioms MahlerLean.not_liouville_of_eventual_target_avoidance
#print axioms MahlerLean.exists_target_block
#print axioms MahlerLean.target_avoidance_from_blocks
#print axioms MahlerLean.exists_escape_of_fusion_data
#print axioms MahlerLean.safeCenter_avoidance_of_deriv_bound

#print axioms MahlerLean.exists_interval_avoiding_finset
#print axioms MahlerLean.exists_interval_avoiding_zeros_and_center
#print axioms MahlerLean.exists_next_interval_in_parent
#print axioms MahlerLean.middle_third_length
#print axioms MahlerLean.targetCutoff_pow97
#print axioms MahlerLean.half_le_nat_floor
#print axioms MahlerLean.nextCutoff_le_targetCutoff
#print axioms MahlerLean.nextCutoff_gt
#print axioms MahlerLean.fusionRadius_le_source_accuracy
#print axioms MahlerLean.nextCutoff_tail_le
#print axioms MahlerLean.tail_smallness_next
#print axioms MahlerLean.exists_large_fusion_scale
#print axioms MahlerLean.successor_from_safe_center
#print axioms MahlerLean.successor_from_counting

#print axioms MahlerLean.exists_initial_tail_cutoff
#print axioms MahlerLean.exists_initial_fusion_stage
#print axioms MahlerLean.exists_fusion_transition
#print axioms MahlerLean.fusionStages_succ
#print axioms MahlerLean.exists_fusion_construction
#print axioms MahlerLean.fusion_intersection_subsingleton
#print axioms MahlerLean.exists_unique_fusion_point
#print axioms MahlerLean.fusion_denominators_tendsto
#print axioms MahlerLean.exists_escape_of_counting

#print axioms MahlerLean.rational_separation
#print axioms MahlerLean.denominator_block_separation
#print axioms MahlerLean.card_le_of_separated_values
#print axioms MahlerLean.rational_interval_card_le
#print axioms MahlerLean.sourceFractions_card_le
#print axioms MahlerLean.sourceFractions_card_le_one
#print axioms MahlerLean.rational_ordConnected_card_le_volume
#print axioms MahlerLean.rational_union_card_le_volume
#print axioms MahlerLean.rational_union_card_le

#print axioms MahlerLean.mem_reducedNumerators
#print axioms MahlerLean.integer_interval_card_discrepancy
#print axioms MahlerLean.multiples_interval_card
#print axioms MahlerLean.multiples_interval_discrepancy
#print axioms MahlerLean.coprime_indicator_moebius
#print axioms MahlerLean.reducedNumerators_card_moebius
#print axioms MahlerLean.totient_eq_moebius_sum
#print axioms MahlerLean.reducedNumerators_card_discrepancy
#print axioms MahlerLean.sourceFractions_card_eq_sum_numerators
#print axioms MahlerLean.sourceFractions_totient_discrepancy
#print axioms MahlerLean.sourceFractions_card_ge_totient_sub_divisors
#print axioms MahlerLean.reciprocal_squares_except_four_le
#print axioms MahlerLean.positive_multiples_card
#print axioms MahlerLean.noncoprime_pairs_card_le
#print axioms MahlerLean.coprime_triangle_card
#print axioms MahlerLean.coprime_pairs_card_le_twice_totient_sum
#print axioms MahlerLean.totient_sum_lower
#print axioms MahlerLean.totient_sum_upper
#print axioms MahlerLean.totient_sum_range_succ
#print axioms MahlerLean.totient_block_lower
#print axioms MahlerLean.divisors_card_le_twice_sqrt
#print axioms MahlerLean.block_divisors_card_le
#print axioms MahlerLean.sourceFractions_card_lower_explicit
#print axioms MahlerLean.sourceFractions_quarter_supply
#print axioms MahlerLean.exists_source_supply_threshold
#print axioms MahlerLean.exists_escape_of_uniform_counting
#print axioms MahlerLean.analytic_zeros_finite_on_compact
#print axioms MahlerLean.exists_analytic_zero_finset
#print axioms MahlerLean.exists_pos_abs_lower_bound
#print axioms MahlerLean.exists_uniform_pos_abs_lower_bound
#print axioms MahlerLean.exists_interval_analytic_family_separated
#print axioms MahlerLean.wronskian_analytic
#print axioms MahlerLean.rationalFamily_analytic
#print axioms MahlerLean.rationalWronskian_analytic
#print axioms MahlerLean.rationalWronskian_zeros_finite
#print axioms MahlerLean.exists_rationalWronskian_zero_finset
#print axioms MahlerLean.exists_interval_rationalWronskians_separated
#print axioms MahlerLean.wronskianDegreeCutoff_monotone
#print axioms MahlerLean.mem_wronskian_zeroSet
#print axioms MahlerLean.wronskian_zeroSet_mono
#print axioms MahlerLean.exists_escape_of_wronskian_counting

#print axioms MahlerLean.largeTargetDegree_lower
#print axioms MahlerLean.largeTargetDegree_upper
#print axioms MahlerLean.largeTargetDegree_ge_two
#print axioms MahlerLean.largeTargetDegree_add_u_le
#print axioms MahlerLean.largeTargetDegree_le_wronskianCutoff
#print axioms MahlerLean.largeTargetN_cast
#print axioms MahlerLean.largeTargetDen_eq_N_minus_one
#print axioms MahlerLean.largeTargetDen_pos
#print axioms MahlerLean.largeTargetDen_le_35u
#print axioms MahlerLean.largeTargetKappa_le
#print axioms MahlerLean.largeTargetN_ratio_nonneg
#print axioms MahlerLean.largeTargetN_ratio_le_two
#print axioms MahlerLean.largeTargetKappa_mul_N_le_96u
#print axioms MahlerLean.largeTargetS_ge_97u
#print axioms MahlerLean.largeTargetPerturbationGap
#print axioms MahlerLean.largeTargetPerturbationGap_one_fifth
#print axioms MahlerLean.largeTargetFareyExponent
#print axioms MahlerLean.largeTargetFareyExponent_gt_two
#print axioms MahlerLean.largeTargetParameterBundle

#print axioms MahlerLean.jetMatrix_det
#print axioms MahlerLean.jetApply_eq_mulVec
#print axioms MahlerLean.jetL1_nonneg
#print axioms MahlerLean.jetApply_continuousOn
#print axioms MahlerLean.jetL1_continuousOn
#print axioms MahlerLean.jetL1_pos_of_wronskian_ne_zero
#print axioms MahlerLean.exists_uniform_jetL1_lower_bound
#print axioms MahlerLean.exists_uniform_jetL1_lower_bound_of_analytic
#print axioms MahlerLean.exists_rationalFamily_uniform_jetL1_lower_bound

#print axioms MahlerLean.exists_pos_lower_bound_on_compact
#print axioms MahlerLean.exists_uniform_jet_coordinate_lower_bound
#print axioms MahlerLean.exists_uniform_jet_coordinate_lower_bound_of_analytic
#print axioms MahlerLean.exists_rationalFamily_uniform_jet_coordinate_lower_bound

-- Step 11: one-dimensional sublevel estimate
#print axioms MahlerLean.exists_iteratedDeriv_succ_eq_zero
#print axioms MahlerLean.exists_iteratedDeriv_succ_eq_zero_of_endpoints
#print axioms MahlerLean.iteratedDeriv_ne_zero_of_abs_lower_bound
#print axioms MahlerLean.exists_interlaced_deriv_zeros
#print axioms MahlerLean.exists_interlaced_iteratedDeriv_zeros
#print axioms MahlerLean.exists_iteratedDeriv_add_eq_zero_of_many_zeros
#print axioms MahlerLean.exists_iteratedDeriv_eq_zero_of_many_zeros
#print axioms MahlerLean.not_exists_many_zeros_of_iteratedDeriv_ne_zero
#print axioms MahlerLean.not_exists_many_zeros_of_iteratedDeriv_abs_lower_bound
#print axioms MahlerLean.not_exists_many_level_hits_of_iteratedDeriv_ne_zero
#print axioms MahlerLean.not_exists_many_level_hits_of_iteratedDeriv_abs_lower_bound
#print axioms MahlerLean.norm_fwdDiff_iter_le_two_pow_mul
#print axioms MahlerLean.hasDerivAt_fwdDiff_iter
#print axioms MahlerLean.exists_fwdDiff_iter_eq_pow_mul_iteratedDeriv
#print axioms MahlerLean.sublevel_interval_power_bound
#print axioms MahlerLean.sublevel_interval_length_bound
#print axioms MahlerLean.level_hit_finset_card_le
#print axioms MahlerLean.level_hit_set_finite
#print axioms MahlerLean.two_level_set_finite_and_ncard_le
#print axioms MahlerLean.abs_boundary_set_finite_and_ncard_le
#print axioms MahlerLean.sublevel_gap_measure_bound
#print axioms MahlerLean.sublevel_measure_le_of_boundary_finset_aux
#print axioms MahlerLean.sublevel_measure_bound

-- Step 12a: analytic linear-combination bridge
#print axioms MahlerLean.analyticOnNhd_jetLinearCombo
#print axioms MahlerLean.iteratedDeriv_jetLinearCombo_eq_jetApply
#print axioms MahlerLean.analyticFamily_linearCombo_smooth

-- Step 12b: local persistence on coefficient/source product space
#print axioms MahlerLean.exists_nhds_iteratedDeriv_abs_lower_bound
#print axioms MahlerLean.exists_product_nhds_jetApply_abs_lower_bound
#print axioms MahlerLean.exists_uniform_product_nhds_jetApply_lower_bound_of_analytic

-- Step 12c: finite compact product cover
#print axioms MahlerLean.mem_coefficientSourceProduct
#print axioms MahlerLean.jetApply_continuousAt_of_analytic
#print axioms MahlerLean.exists_product_nhds_jetApply_abs_lower_bound_of_analytic
#print axioms MahlerLean.exists_finite_uniform_jet_product_cover_of_analytic

-- Step 12d: local uniform sublevel bridge
#print axioms MahlerLean.sublevel_set_eq_empty_of_abs_lower_bound
#print axioms MahlerLean.sublevel_measure_eq_zero_of_abs_lower_bound
#print axioms MahlerLean.jetLinearCombo_sublevel_measure_bound
#print axioms MahlerLean.jetLinearCombo_sublevel_eq_empty_of_zero_order
#print axioms MahlerLean.jetLinearCombo_local_sublevel_control

-- Step 12e: finite quantitative assembly
#print axioms MahlerLean.rpow_inv_nat_le_rpow_inv_nat
#print axioms MahlerLean.jetLinearCombo_sublevel_measure_bound_uniform_order
#print axioms MahlerLean.measureReal_le_card_mul_of_finite_cover
#print axioms MahlerLean.jetLinearCombo_sublevel_measure_bound_of_finite_interval_cover
#print axioms MahlerLean.jetLinearCombo_sublevel_measure_bound_uniform
#print axioms MahlerLean.jetLinearCombo_sublevel_measure_bound_of_finite_interval_cover_all_orders

-- Step 12f: uniform compact interval patches
#print axioms MahlerLean.exists_product_nhds_Icc_subset
#print axioms MahlerLean.exists_finite_uniform_jet_interval_cover_of_analytic

-- Step 12g: global uniform sublevel measure estimate
#print axioms MahlerLean.exists_uniform_analytic_sublevel_measure_bound


-- Uniform interval covers and rational-relation specialization
#print axioms MahlerLean.sublevel_ordConnected_of_no_level
#print axioms MahlerLean.sublevel_interval_cover_of_boundary_finset
#print axioms MahlerLean.sublevel_interval_cover_of_derivative_bound
#print axioms MahlerLean.jetLinearCombo_interval_cover
#print axioms MahlerLean.exists_uniform_analytic_sublevel_interval_cover
#print axioms MahlerLean.exists_uniform_analytic_sublevel_bound
#print axioms MahlerLean.exists_uniform_rational_relation_sublevel_bound

#print axioms MahlerLean.determinant_lower_bound_of_integral_rows
#print axioms MahlerLean.targetLinearMatrix_clear_entry
#print axioms MahlerLean.targetLinearMatrix_cleared_det
#print axioms MahlerLean.targetLinearMatrix_det_lower
#print axioms MahlerLean.targetLinearMatrix_det_lower_dyadic
#print axioms MahlerLean.targetLinearMatrix_det_eq_zero_of_lt

-- Step 13: determinant analytic groundwork
#print axioms MahlerLean.matrix_entry_le_rowL1
#print axioms MahlerLean.abs_det_le_sum_perm_prod_rowL1
#print axioms MahlerLean.abs_det_le_perm_card_mul_pow
#print axioms MahlerLean.targetLinearPerturbation_apply
#print axioms MahlerLean.abs_targetLinearPerturbation_le
#print axioms MahlerLean.targetLinearPerturbation_l1_le
#print axioms MahlerLean.perturbation_exponent_identity
#print axioms MahlerLean.perturbation_exponent_ge

-- Step 13: uniform vector Taylor remainder
#print axioms MahlerLean.exists_taylor_remainder_bound_nonneg
#print axioms MahlerLean.taylor_remainder_le_radius
#print axioms MahlerLean.exists_taylor_remainder_bound_on_radius
#print axioms MahlerLean.exists_curve_taylor_remainder_bound
#print axioms MahlerLean.taylorWithinEval_eq_derivative_sum

-- Step 13: target-linear curve Taylor specialization
#print axioms MahlerLean.targetLinearCurve_apply
#print axioms MahlerLean.targetLinearMatrix_row_eq_curve
#print axioms MahlerLean.targetLinearCurve_contDiffOn
#print axioms MahlerLean.exists_targetLinearCurve_taylor_remainder_bound

-- Step 13: perturbation matrix interface
#print axioms MahlerLean.targetLinearMatrix_eq_add_perturbation
#print axioms MahlerLean.targetLinearPerturbationMatrix_rowL1_le
#print axioms MahlerLean.abs_det_targetLinearPerturbationMatrix_le

-- Step 13: Taylor-polynomial determinant factorization
#print axioms MahlerLean.taylorPolynomialMatrix_eq_mul
#print axioms MahlerLean.det_taylorPolynomialMatrix_eq_mul
#print axioms MahlerLean.taylorCoefficientMatrix_transpose_rowL1_le
#print axioms MahlerLean.abs_det_taylorCoefficientMatrix_le
#print axioms MahlerLean.abs_det_taylorPolynomialMatrix_le

-- Step 13: alternating Taylor expansion
#print axioms MahlerLean.det_sum_rows_eq_sum_det
#print axioms MahlerLean.det_rows_eq_zero_of_not_injective
#print axioms MahlerLean.fin_val_le_of_strictMono
#print axioms MahlerLean.triangular_le_sum_of_injective
#print axioms MahlerLean.abs_det_taylor_sum_le

-- Step 13: Taylor remainder row expansion
#print axioms MahlerLean.abs_det_le_perm_card_mul_one_row
#print axioms MahlerLean.derivativeDeterminantSum_nonneg
#print axioms MahlerLean.abs_det_le_derivativeDeterminantSum
#print axioms MahlerLean.abs_det_taylorWithinEval_le
#print axioms MahlerLean.det_add_rows_eq_sum_bool
#print axioms MahlerLean.abs_det_add_le_of_remainder_rows

-- Step 13: uniform smooth-curve determinant decay
#print axioms MahlerLean.matrixRowL1_le_card_mul_norm
#print axioms MahlerLean.curveValueMatrix_eq_taylor_add_remainder
#print axioms MahlerLean.matrixRowL1_sub_le
#print axioms MahlerLean.curveTaylorRemainderMatrix_rowL1_le
#print axioms MahlerLean.abs_det_curveValueMatrix_le_of_taylor
#print axioms MahlerLean.exists_targetLinearCurve_determinant_bound

-- Step 13: vertical stability and arithmetic comparison
#print axioms MahlerLean.abs_det_targetLinearMatrix_le_graph_add_error
#print axioms MahlerLean.exists_targetLinearCurve_rowL1_bound
#print axioms MahlerLean.exists_targetLinearMatrix_analytic_upper_bound
#print axioms MahlerLean.exists_targetLinearMatrix_det_zero_of_clustered_approximations


-- Step 13: rank, normalized relations, disjoint sublevels and counting
#print axioms MahlerLean.exists_unit_relation_of_all_det_zero
#print axioms MahlerLean.exists_unit_targetLinear_relation_of_all_det_zero
#print axioms MahlerLean.norm_targetLinear_graph_relation_le_of_approx
#print axioms MahlerLean.exists_unit_targetLinear_graph_sublevel_of_all_det_zero
#print axioms MahlerLean.exists_uniform_analytic_sublevel_disjoint_interval_cover
#print axioms MahlerLean.exists_uniform_analytic_disjoint_sublevel_bound
#print axioms MahlerLean.exists_uniform_rational_relation_disjoint_sublevel_bound
#print axioms MahlerLean.exists_uniform_sublevel_data_of_targetLinear_det_zero
#print axioms MahlerLean.exists_targetLinear_counting_bound_of_all_det_zero

#print axioms MahlerLean.card_le_sum_of_finite_cover
#print axioms MahlerLean.card_le_of_uniform_cell_bound
#print axioms MahlerLean.eventually_log_mul_large_block_power_le

-- Mixed perturbation: fixed-base analytic bounds and uniform scalar threshold
#print axioms MahlerLean.mixed_perturbation_term_le
#print axioms MahlerLean.mixed_perturbation_sum_le
#print axioms MahlerLean.abs_det_add_le_mixed_sum
#print axioms MahlerLean.abs_det_add_le_triangular_of_mixed_bounds
#print axioms MahlerLean.perturbation_small_of_exponent_gap
#print axioms MahlerLean.largeTarget_vertical_error_le_radius_power
#print axioms MahlerLean.exists_uniform_smooth_curve_minor_bound
#print axioms MahlerLean.abs_det_le_error_power_of_good_minors
#print axioms MahlerLean.exists_smooth_curve_mixed_bound
#print axioms MahlerLean.exists_smooth_curve_perturbed_sum_bound
#print axioms MahlerLean.exists_smooth_curve_strong_perturbed_bound
#print axioms MahlerLean.exists_targetLinearMatrix_strong_perturbed_bound

-- Uniformity in moving cells and adaptive degrees
#print axioms MahlerLean.iteratedDerivWithin_right_subinterval
#print axioms MahlerLean.exists_uniform_derivative_bound_right_subinterval
#print axioms MahlerLean.exists_uniform_taylor_remainder_moving_base
#print axioms MahlerLean.exists_moving_base_curve_determinant_bound
#print axioms MahlerLean.exists_moving_base_smooth_curve_minor_bound
#print axioms MahlerLean.exists_moving_base_curve_mixed_bound
#print axioms MahlerLean.exists_moving_base_curve_perturbed_sum_bound
#print axioms MahlerLean.exists_moving_base_curve_strong_perturbed_bound
#print axioms MahlerLean.exists_targetLinearMatrix_uniform_perturbed_bound
#print axioms MahlerLean.exists_targetLinearMatrix_uniform_degree_bound
#print axioms MahlerLean.exists_targetLinearMatrix_det_zero_uniform_cells

-- Uniform large-target scales and rational witnesses
#print axioms MahlerLean.strict_power_comparison
#print axioms MahlerLean.degree_denominator_factor_le
#print axioms MahlerLean.largeTarget_determinant_exponent_gap
#print axioms MahlerLean.two_height_denominator_eq
#print axioms MahlerLean.determinant_scale_comparison
#print axioms MahlerLean.exists_largeTarget_det_zero_uniform_threshold
#print axioms MahlerLean.exists_largeTarget_witnesses_all_det_zero
#print axioms MahlerLean.exists_largeTarget_cell_counting_data

-- Uniform finite-degree sublevel constants and per-cell counting
#print axioms MahlerLean.exists_uniform_degree_counting_data
#print axioms MahlerLean.scaled_error_le_uniform_coefficient
#print axioms MahlerLean.scaled_error_lt_of_uniform_threshold
#print axioms MahlerLean.sublevel_power_le_uniform_decay
#print axioms MahlerLean.farey_sublevel_bound_le_constant
#print axioms MahlerLean.exists_uniform_largeTarget_cell_counting_bound
#print axioms MahlerLean.exists_uniform_largeTarget_cell_card_bound
#print axioms MahlerLean.exists_uniform_largeTarget_interval_cell_card_bound

-- Source cells and all large dyadic blocks, with the original margin
#print axioms MahlerLean.exists_source_cell_cover
#print axioms MahlerLean.exists_uniform_largeTarget_block_card_bound
#print axioms MahlerLean.dyadic_index_lt_uniform_count
#print axioms MahlerLean.uniform_dyadic_count_le_log
#print axioms MahlerLean.large_block_log_exponent
#print axioms MahlerLean.exists_largeTarget_dyadic_card_bound
#print axioms MahlerLean.safetyMargin_le_largeTarget_error
#print axioms MahlerLean.witness_rational_den_le
#print axioms MahlerLean.exists_largeTarget_original_margin_card_bound

-- Small-target witnesses, packing and uniform dyadic sums
#print axioms MahlerLean.rational_target_neighborhood_card_le
#print axioms MahlerLean.mem_targetWitnessBox
#print axioms MahlerLean.targetWitnessBox_card_le
#print axioms MahlerLean.safetyMargin_le_two_add_four
#print axioms MahlerLean.target_witness_numerator_bound
#print axioms MahlerLean.safetyMargin_le_block
#print axioms MahlerLean.dyadic_inverse_power_sum_le
#print axioms MahlerLean.dyadic_square_partial_sum_le
#print axioms MahlerLean.dyadic_square_sum_le
#print axioms MahlerLean.small_target_block_card_le_raw
#print axioms MahlerLean.small_target_block_card_le
#print axioms MahlerLean.exists_smallTarget_original_margin_card_bound
#print axioms MahlerLean.inverse_bound_of_abs_deriv_lower
#print axioms MahlerLean.exists_smallTarget_counting_of_derivative_bounds

-- Complete two-height assembly and the fusion counting interface
#print axioms MahlerLean.exists_dyadic_target_block
#print axioms MahlerLean.hasTargetWitness_small_or_large
#print axioms MahlerLean.proposition_5_1_of_fixed_bounds
#print axioms MahlerLean.proposition_5_1
#print axioms MahlerLean.proposition_5_1_uniformDangerBound

-- Proposition 5.1 discharges the counting input of analytic fusion
#print axioms MahlerLean.exists_escape_of_analytic_wronskians

-- Derivative localization and escape in arbitrary open subsets
#print axioms MahlerLean.exists_deriv_ne_zero_of_analytic_nonconstant
#print axioms MahlerLean.exists_analytic_derivative_interval
#print axioms MahlerLean.exists_escape_of_nonconstant_analytic_wronskians
#print axioms MahlerLean.exists_escape_in_open_of_analytic_wronskians

-- Rational relations, cancellation and the original nonrationality hypothesis
#print axioms MahlerLean.polynomial_eq_zero_on_open
#print axioms MahlerLean.isRationalOn_of_polynomial_relation
#print axioms MahlerLean.polynomial_relation_eq_zero_of_not_rational
#print axioms MahlerLean.nonconstant_of_not_rational
#print axioms MahlerLean.exists_escape_of_not_rational_and_wronskians

-- Independence of the exact rational family and its analytic germs
#print axioms MahlerLean.relationPolynomial_coeff
#print axioms MahlerLean.relationPolynomial_eval
#print axioms MahlerLean.rationalFamily_linearIndependent_of_not_rational
#print axioms MahlerLean.rationalFamily_coeff_eq_zero_of_eventually_sum_eq_zero

-- Taylor orders and the algebraic leading matrix for the Wronskian criterion
#print axioms MahlerLean.eventually_zero_of_all_iteratedDeriv_zero
#print axioms MahlerLean.rationalFamily_exists_nonzero_derivative
#print axioms MahlerLean.rationalFamily_exists_first_nonzero_derivative
#print axioms MahlerLean.det_descFactorial_eq_vandermonde
#print axioms MahlerLean.det_descFactorial_ne_zero

-- Adapted Taylor basis and constant Wronskian basis changes
#print axioms MahlerLean.exists_basis_distinct_orders
#print axioms MahlerLean.iteratedDeriv_analytic_sum
#print axioms MahlerLean.rationalFamily_exists_basis_distinct_orders
#print axioms MahlerLean.wronskian_linearCombination_matrix
#print axioms MahlerLean.wronskian_basis_ne_zero_iff

-- Analytic Wronskian leading term and discharge of nontriviality
#print axioms MahlerLean.tendsto_div_pow_of_analytic_vanishing
#print axioms MahlerLean.tendsto_scaled_iteratedDeriv
#print axioms MahlerLean.det_scaled_derivatives
#print axioms MahlerLean.tendsto_wronskian_leading_coefficient
#print axioms MahlerLean.wronskian_leading_coefficient_ne_zero
#print axioms MahlerLean.tendsto_wronskian_div_zpow
#print axioms MahlerLean.eventually_wronskian_ne_zero_of_distinct_orders
#print axioms MahlerLean.sum_indices_le_sum_distinct_orders
#print axioms MahlerLean.tendsto_wronskian_div_pow
#print axioms MahlerLean.eventually_rationalWronskian_ne_zero_of_not_rational
#print axioms MahlerLean.exists_rationalWronskian_ne_zero_of_not_rational
#print axioms MahlerLean.exists_escape_of_analytic_not_rational
