import MahlerLean

#print axioms MahlerLean.dyadic_exponent_identity
#print axioms MahlerLean.remainder_exponent_lt_two
#print axioms MahlerLean.farey_exponent_gt_two
#print axioms MahlerLean.perturbation_gap
#print axioms MahlerLean.fusion_exponent_identity
#print axioms MahlerLean.fusion_exponent_negative
#print axioms MahlerLean.exists_safe_center
#print axioms MahlerLean.counting_budget
#print axioms MahlerLean.safety_transfer

#print axioms MahlerLean.mem_sourceFractions
#print axioms MahlerLean.isSafeCenter_iff_no_witness
#print axioms MahlerLean.isSafeCenter_iff_not_mem_dangerousSources
#print axioms MahlerLean.eventually_subquadratic_quarter
#print axioms MahlerLean.exists_safeCenter_of_quarter_bounds
#print axioms MahlerLean.safe_center_of_counting_estimates
#print axioms MahlerLean.safeCenter_avoidance_of_movement

#print axioms MahlerLean.liouville_iff_paperLiouville
#print axioms MahlerLean.liouville_of_source_approximations
#print axioms MahlerLean.not_liouville_of_eventual_target_avoidance
#print axioms MahlerLean.exists_target_block
#print axioms MahlerLean.target_avoidance_from_blocks
#print axioms MahlerLean.exists_escape_of_fusion_data
#print axioms MahlerLean.safeCenter_avoidance_of_deriv_bound

#print axioms MahlerLean.exists_interval_avoiding_finset
#print axioms MahlerLean.exists_interval_avoiding_zeros_and_center
#print axioms MahlerLean.exists_next_interval_in_parent
#print axioms MahlerLean.middle_third_length
#print axioms MahlerLean.targetCutoff_pow97
#print axioms MahlerLean.half_le_nat_floor
#print axioms MahlerLean.nextCutoff_le_targetCutoff
#print axioms MahlerLean.nextCutoff_gt
#print axioms MahlerLean.fusionRadius_le_source_accuracy
#print axioms MahlerLean.nextCutoff_tail_le
#print axioms MahlerLean.tail_smallness_next
#print axioms MahlerLean.exists_large_fusion_scale
#print axioms MahlerLean.successor_from_safe_center
#print axioms MahlerLean.successor_from_counting

#print axioms MahlerLean.exists_initial_tail_cutoff
#print axioms MahlerLean.exists_initial_fusion_stage
#print axioms MahlerLean.exists_fusion_transition
#print axioms MahlerLean.fusionStages_succ
#print axioms MahlerLean.exists_fusion_construction
#print axioms MahlerLean.fusion_intersection_subsingleton
#print axioms MahlerLean.exists_unique_fusion_point
#print axioms MahlerLean.fusion_denominators_tendsto
#print axioms MahlerLean.exists_escape_of_counting

#print axioms MahlerLean.rational_separation
#print axioms MahlerLean.denominator_block_separation
#print axioms MahlerLean.card_le_of_separated_values
#print axioms MahlerLean.rational_interval_card_le
#print axioms MahlerLean.sourceFractions_card_le
#print axioms MahlerLean.sourceFractions_card_le_one
#print axioms MahlerLean.rational_ordConnected_card_le_volume
#print axioms MahlerLean.rational_union_card_le_volume
#print axioms MahlerLean.rational_union_card_le
